version: '3.8'
services:

   # Web Server Service
  notification_nginx:
    image: nginx:alpine
    container_name: notification_nginx
    ports:
      - "8001:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - notification_app
    networks:
      - nextbasket
    


  #Database Service
  notification__db:
    image : mysql
    container_name : notification_db
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: notification
      MYSQL_ROOT_PASSWORD: password
    restart: unless-stopped
    networks:
      - nextbasket

  # Application Service
  notification_app:
    container_name: notification_app
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9001:9000"
    working_dir: /var/www
    networks:
      - nextbasket

networks:
    nextbasket:
      external: true 




